<table class="tfo-notebook-buttons" align="left">

  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1yrdikxLYAgJewvvsI_laTVIoomo-mmJP?usp=sharing"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Click here to run in Google Colab</a>
  </td>

</table>

#  A classification problem

In [1]:
# Import modules to be used later
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
# Download data if it doesn't exist in the folder
!pip install wget
import wget
wget.download('https://raw.githubusercontent.com/NHERI-SimCenter/SimCenterAI_Workshop2021/master/notebooks/day1/Building_in_Hurricane.csv')

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=999ab133c061cada856b729255e611cf27aa930c1afc26263623ec7ddb4d09c4
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

'Building_in_Hurricane.csv'

## 1. Load data

In [3]:
# Read data into a pandas dataframe
all_data = pd.read_csv("Building_in_Hurricane.csv")
all_data

,overall_building_condition,max_mph,age_yrs,number_of_stories,roof_shape,roof_cover,wall_cladding,structural_framing_system
0,0,80,14.0,1.0,Complex,Tile (clay),Stucco,Wood-frame
1,1,80,29.0,2.0,Gable,Tile (clay),Stucco,Wood-frame
2,0,85,27.0,2.0,Complex,Tile (clay),Stucco,Wood-frame
3,1,85,24.0,1.0,Hip,Asphalt shingles (laminated),Stucco,Wood-frame
4,1,85,30.0,2.0,Gable,Asphalt shingles (laminated),Wood Siding,Wood-frame
...,...,...,...,...,...,...,...,...
921,1,95,40.0,1.0,Gambrel,Asphalt shingles (3-tab),Wood Siding,Wood-frame
922,1,90,38.0,1.0,Gable,Asphalt shingles (3-tab),Wood Siding,Wood-frame
923,1,105,22.0,2.0,Gable,Asphalt shingles (3-tab),Vinyl Siding,Wood-frame
924,0,100,16.0,1.0,Hip,Asphalt shingles (3-tab),Stucco,Wood-frame
925,2,105,50.0,2.0,Gable,Asphalt shingles (3-tab),Wood Siding,Wood-frame

Our task is to fit a model:


**input** ['max_mph', 'age_yrs', 'number_of_stories',
       'roof_shape', 'roof_cover', 'wall_cladding',
       'structural_framing_system']


**output** ['overall_building_condition']

## 2. Data preprocessing
### Prepare input and output data

In [5]:
X = all_data.iloc[:, [1,2,3,4,5,6,7]].values
Y = all_data.iloc[:, 0]

print('X shape: ', X.shape)
print('X: ', X)
print('y shape: ', Y.shape)
print('Y: ', Y)

X shape:  (926, 7)
X:  [[80 14.0 1.0 ... 'Tile (clay)' 'Stucco' 'Wood-frame']
 [80 29.0 2.0 ... 'Tile (clay)' 'Stucco' 'Wood-frame']
 [85 27.0 2.0 ... 'Tile (clay)' 'Stucco' 'Wood-frame']
 ...
 [105 22.0 2.0 ... 'Asphalt shingles (3-tab)' 'Vinyl Siding' 'Wood-frame']
 [100 16.0 1.0 ... 'Asphalt shingles (3-tab)' 'Stucco' 'Wood-frame']
 [105 50.0 2.0 ... 'Asphalt shingles (3-tab)' 'Wood Siding' 'Wood-frame']]
y shape:  (926,)
Y:  0      0
1      1
2      0
3      1
4      1
      ..
921    1
922    1
923    1
924    0
925    2
Name: overall_building_condition, Length: 926, dtype: int64

In [6]:
Y.value_counts()

overall_building_condition
1    441
0    288
2    197
Name: count, dtype: int64

### Encode categorical variables

In [7]:
# Encoding Categorical Variables
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

X[:,3] = le.fit_transform(X[:,3]) #roof_shape
X[:,4] = le.fit_transform(X[:,4]) #roof_cover
X[:,5] = le.fit_transform(X[:,5]) #wall_cladding
X[:,6] = le.fit_transform(X[:,6]) #structural_framing_system

### Split into train and test sets

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=1993)

print('X_train shape: ', X_train.shape)
print('Y_train shape: ', Y_train.shape)
print('X_test shape: ', X_test.shape)
print('Y_test shape: ', Y_test.shape)

X_train shape:  (740, 7)
Y_train shape:  (740,)
X_test shape:  (186, 7)
Y_test shape:  (186,)

## 3. MODEL

## 3.1 Multilayer Perceptron (Neural Network)

In [9]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

In [10]:
# Build and train a neural network with 1 hidden layer of 10 perceptrons
model = MLPClassifier(hidden_layer_sizes=(10,),max_iter=2000)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
f1 = f1_score(Y_test.to_numpy(),Y_pred, average='micro')
print(f1)

0.5645161290322581

In [11]:
# Build and train a neural network with 2 hidden layers: the first layer has 20 perceptrons, the second has 30 perceptrons
model = MLPClassifier(hidden_layer_sizes=(20, 30),max_iter=2000)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
f1 = f1_score(Y_test.to_numpy(),Y_pred, average='micro')
print(f1)

0.6075268817204301

## 3.2. Your assignment

Build and train 5 neural networks for the above data, with increasing layers and perceptrons.


Print the f1 score of them.


And, based on the f1 scores, can you make a conclusion:


Is it always good to increase the complexity of a model?

In [12]:
# You code here:
model = MLPClassifier(hidden_layer_sizes=(10, 10, 10, 10, 10),max_iter=2000)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)
f1 = f1_score(Y_test.to_numpy(),Y_pred, average='micro')
print(f1)

0.5913978494623656

You conclusion here (double click here to edit):By increasing the complexity of a model, you get a more diverse range of answers, ultimately allowing the f1 score to become more accurate.

When you finish, don't forget to save this notebook. Then download it as a .ipynb and submit it.